package:
  name: menpo3d
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo >=0.7.6,<0.8
    - cyrasterize 0.3.*
    - mayavi 4.5.*
    - scikit-sparse 0.3.*  # [linux]
    - qt 4.*

test:
  requires:
    - nose
    - mock

  imports:
    - menpo3d

  commands:
    - nosetests menpo3d -v

about:
  home: https://github.com/menpo/menpo3d/
  license: BSD
