package:
  name: menpo3d
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo # 0.4.0 upon release
    - cyassimp 0.2.0
    - cyrasterize 0.2.0
    - menpo-pyvrml97 2.3.0a4  # [py27]
    - mayavi 4.3.1  # [py27]
test:
  requires:
  - nose
  - mock

  imports:
  - menpo3d

  commands:
  - python -c "import nose; nose.main()" -s menpo3d

about:
  home: https://github.com/menpo/menpo3d/
  license: BSD
