package:
  name: menpo3d
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo >=0.6,<0.7
    - cyassimp 0.2.*
    - cyrasterize >=0.2.4,<0.3
    - menpo-pyvrml97 2.3.0a4  # [py2k]
    - mayavi >=4.4.4

test:
  requires:
  - nose
  - mock 1.3.0

  imports:
  - menpo3d

about:
  home: https://github.com/menpo/menpo3d/
  license: BSD
